"""Added Company table

Revision ID: e4e889cd7cef
Revises: 
Create Date: 2024-05-06 21:38:55.293725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e889cd7cef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('locality', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('current_employee_estimate', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('row')
    )
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
